# Generated by Django 2.2.4 on 2019-10-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flying_from', models.CharField(max_length=50)),
                ('flying_to', models.CharField(max_length=50)),
                ('departing', models.DateField()),
                ('returning', models.DateField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('travel_class', models.CharField(max_length=50)),
            ],
        ),
    ]
