# Generated by Django 2.2.4 on 2019-10-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plane_ID', models.CharField(max_length=50)),
                ('F', models.CharField(max_length=50)),
                ('T', models.CharField(max_length=50)),
                ('Departure_Time', models.CharField(max_length=50)),
                ('Arrival_Time', models.CharField(max_length=50)),
                ('Departure_City', models.CharField(max_length=50)),
                ('Arrival_City', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
