# Generated by Django 2.2.4 on 2019-11-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_flights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Person', models.CharField(max_length=5)),
                ('Phone', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
    ]
