# Generated by Django 2.2.4 on 2019-11-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
