# Generated by Django 2.2.4 on 2019-11-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
